### ISSUE TITLE
Create 1.0.0 release

### ISSUE THREAD

**Issue by IGx89** [adobe/xamarin-acpgriffon#23]
Hi! Most of the other packages are at 1.0.0 now (see https://github.com/adobe/xamarin-acpcore/issues/24). Our business is wanting to use Project Griffon, but I'm not sure if it's going to work given that we're using ACPCore v1.0.0 while this uses ACPCore v0.0.1. We'll see I guess :). To keep everything compatible you'll want to release a v1.0.0 of this library too I'm guessing?

**Comment by rymorale** [comment]
Hi @IGx89, the 1.0.0 release is pending in https://github.com/adobe/xamarin-acpgriffon/pull/25. Closing this issue.
